version: '3'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/app
    links:
    - redisai
    command: bash ./scripts/start-dev.sh
  redisai:
    image: redislabs/redisai:edge-cpu-bionic
    ports:
      - "6379:6379"
